### ISSUE TITLE
你好棒

### ISSUE THREAD

**Issue by zackexplosion** [adlerhsieh/docker-kali-linux#1]
Awesome!

**Comment by jywei** [comment]
Why do you put python script code inside docker repo?

**Comment by adlerhsieh** [comment]
Cause this is still a practice and currently I'm too lazy to split the repo

**Comment by adlerhsieh** [comment]
Ok it is resolved with the commit above. Scripts moved to [elsewhere](https://github.com/adlerhsieh/penetration-testing-examples)
